mysql : 
  port : "3306"
  host: "host.docker.internal"
  # host: "172.18.144.1"
  database : "bangjeff"
  user : "root"
  password : "1sampai8"
  path_migrate: file:./db/migration
server :
  port: "8000"
  log_level: "debug"
  prefork:      false
  strict_routing: false
  case_sensitive: false
  body_limit: 4 * 1024 * 1024
  base_path: ""
middleware :
  allows_origin : "*"
default_limit: 10
default_page: 1



